version: '3.5'
services:
  core:
    image: tcimba/misuse-backend
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: on-failure
    volumes:
      - ./data:/root/data
    ports:
      - "9090:9090"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=9090
      - IPINFO_ACCESS_TOKEN=${IPINFO_ACCESS_TOKEN:-}
      - WORKERS=${WORKERS:-4}

